### ISSUE TITLE
Thaumcraft crash on post initialization

### ISSUE THREAD

**Issue by ShadowTrolll** [Azanor/thaumcraft-beta#1489] opened 2018-10-08 16:45 UTC
Hello. I made a modpack what I want to play but thaumcraft crashes on post-initialization phase. Its NOT the " java.lang.IllegalAccessError" 
Thanks for help, here is crash log.
[https://pastebin.com/egjqRGMk](url)

**Comment by wamc2017** [comment] 2018-10-08 16:46
Dupe of #1468

**Closed** 2018-10-11 06:28 UTC
Labels: duplicate
