### ISSUE TITLE
Sand>Tainted Soil>???

### ISSUE THREAD

**Issue by SethosSch** [Azanor/thaumcraft-beta#683] opened 2018-05-08 18:09 UTC
Dirt
![image](https://user-images.githubusercontent.com/6932672/39774630-15edecec-5304-11e8-8d3a-d34d3ab5ba8d.png)

**Comment by androshalforc** [comment] 2018-05-08 22:36
how much flux is in the area?
if you've been doing too much careless alchemy in the area this could easily happen

**Comment by talonos2** [comment] 2018-05-08 22:52
Duplicate of #607 

Sadly it's not a priority for him.

**Comment by androshalforc** [comment] 2018-05-09 02:56
Ahh I misunderstood the issue i thought it was about taint spreading not about turning into sand into dirt

**Closed** 2018-07-19 11:39 UTC
Labels: duplicate
