### ISSUE TITLE
[B23] Golems don't initially render any specialty parts when placed/spawned

### ISSUE THREAD

**Issue by MightyBidoof** [Azanor/thaumcraft-beta#1387] opened 2018-09-01 20:13 UTC
As the title says, the "Specialization" parts (uni-wheel, claw hands etc.) won't render when they're initially placed/spawned. This bug fixes itself upon restarting but could be slightly confusing for some people.

**Comment by Reassembly** [comment] 2018-09-02 14:59
Duplicate of #1138

**Comment by Azanor** [comment] 2018-09-13 12:17
fixed in b24

**Closed by Azanor** 2018-09-13 12:17 UTC
