### ISSUE TITLE
Research crafting requirements can be fulfilled by something being crafted by ANY means, not just the relevant one.

### ISSUE THREAD

**Issue by drhead** [Azanor/thaumcraft-beta#1164] opened 2018-07-18 20:44 UTC
Found this bug using Beta 17.

An example of a research affected is Hedge Alchemy stage 3.  The research requires you to craft a clay blob, a string, a cobweb, and a lava bucket.  While the research seems to intend for these tasks to be done using the crucible, you can fulfill some of these objectives using vanilla recipes (crafting clay into a clay block then back into clay blobs will fulfill the clay requirement) or by using any recipe added by a mod (like using Natura or Harvestcraft's cotton to string recipe, this will fulfill the requirement for string).  It is possible that Hedge Alchemy is the only research affected since few researches require crafting vanilla items.

**Comment by wamc2017** [comment] 2018-07-18 22:49
Dupe of #1112

**Closed** 2018-07-19 11:53 UTC
Labels: duplicate, nothing to do
