### ISSUE TITLE
[B11] Thaumatorium: no recipes available

### ISSUE THREAD

**Issue by GraniteDevil** [Azanor/thaumcraft-beta#602] opened 2018-05-02 01:36 UTC
Playing Beta 11.  I have constructed a Thaumatorium, opened the GUI, placed 1 iron ingot in the available slot but no recipes show up.  I have used various catalysts but no recipes show up.  I have a full jar of Instrumentum (to make a.brass with iron) and have tried both piping it in and using an emptying transfuser but there's no suction with the tubes and the transfuser doesn't take in the essentia.

I don't see that anybody else has had this problem but it's happening to me in an existing survival world, in a new survival world, in creative, and when I pull all the mods out and use *only* Thaumcraft in any kind of new world.  You can just see the burning netherack in the picture.  I used both transfusers just to see what happens and that tubing is going around to the back of the structure (with or w/o tubing though, it just doesn't work).

![image](https://user-images.githubusercontent.com/38897981/39501207-896c1b3a-4d87-11e8-94a5-5461928688bf.png)

**Comment by wamc2017** [comment] 2018-05-02 01:38
Dupe of #513 #586

**Closed** 2018-05-04 12:13 UTC
Labels: bug, solved
