### ISSUE TITLE
[B-17] Crash/cant re-enter single player world after breaking lattice block

### ISSUE THREAD

**Issue by Caopr** [Azanor/thaumcraft-beta#1121] opened 2018-07-07 21:14 UTC
Once a lattice block became clogged I thought right clicking on it with a new would replace it. instead it placed it after it. so after trying to remove the non clogged one to fix the issue my single player game crashed and I haven't been able to open it back up without this crash.

Time: 7/7/18 2:45 AM
Description: Ticking block entity

java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Unknown Source)
	at thaumcraft.common.tiles.devices.TileCondenser.func_73660_a(TileCondenser.java:57)
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1845)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by belathus** [comment] 2018-07-08 04:09
Also, this is probably a duplicate of #1095.

**Comment by Caopr** [comment] 2018-07-08 04:10
Oops sorry then .looked up a few keywords and didint see anything else of it

**Closed** 2018-07-08 05:43 UTC
