### ISSUE TITLE
Reverse Centrifuge *Merging Aspects*

### ISSUE THREAD

**Issue by KlintzC** [Azanor/thaumcraft-beta#1563] opened 2018-11-21 02:32 UTC
I don't know if it's balancing purpose to not make a machine that merges aspects, because I'm sure that @Azanor thought about that.

I have a suggestion of a machine that has to work under pressure to merge aspects. This pressure could be powered with a Redstone Relay and regenerate tons of Flux while merging the aspects.  The machine would need 1 point of each aspect to make 1 secondary aspect. The point lost turns into Flux, also has a chance of 30% of both points turns into Flux, depending on the material that the machine is made (Like the Smelter), and it could take a while to make a good amount of secondary aspect.

These are just some ideas of how to make a machine balanced to merge aspects, a suggestion mainly to make Alienis essentia with no need to go to The End and kill the dragon to farm this aspect.

**Comment by wamc2017** [comment] 2018-11-21 03:35
Dupe of #1436

**Comment by KlintzC** [comment] 2018-11-21 12:09
Closing it, thanks

**Closed as completed** 2018-11-21 12:09 UTC
