### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by Efimero** [Azanor/thaumcraft-beta#1110] opened 2018-07-05 17:07 UTC
it seems the condenser has some issue when being loaded while in use

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  F5FixLoadingPlugin (f5fix-1.1.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 7/5/18 7:03 PM
Description: Ticking block entity

java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at thaumcraft.common.tiles.devices.TileCondenser.func_73660_a(TileCondenser.java:57)
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1845)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.Random.nextInt(Random.java:388)
	at thaumcraft.common.tiles.devices.TileCondenser.func_73660_a(TileCondenser.java:57)

-- Block entity being ticked --
Details:
	Name: thaumcraft:tilecondenser // thaumcraft.common.tiles.devices.TileCondenser
	Block type: ID #450 (tile.condenser // thaumcraft.common.blocks.devices.BlockCondenser)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-194,66,-289), Chunk: (at 14,4,15 in -13,-19; contains blocks -208,0,-304 to -193,255,-289), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Actual block type: ID #450 (tile.condenser // thaumcraft.common.blocks.devices.BlockCondenser)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1832)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Efimero'/379, l='MpServer', x=53.12, y=66.00, z=-65.12]]
	Chunk stats: MultiplayerChunkCache: 1089, 1089
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-4,64,-140), Chunk: (at 12,4,4 in -1,-9; contains blocks -16,0,-144 to -1,255,-129), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 2990185 game time, 3870546 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 54 total; [EntityRabbit['Rabbit'/274, l='MpServer', x=53.50, y=64.00, z=-127.63], EntityBat['Bat'/276, l='MpServer', x=54.30, y=23.95, z=-38.40], EntityRabbit['Rabbit'/277, l='MpServer', x=51.44, y=79.00, z=-6.20], EntityRabbit['Rabbit'/278, l='MpServer', x=51.66, y=79.00, z=-6.65], EntityRabbit['Rabbit'/279, l='MpServer', x=59.61, y=82.00, z=5.00], EntityPlayerSP['Efimero'/379, l='MpServer', x=53.12, y=66.00, z=-65.12], EntityRabbit['Rabbit'/295, l='MpServer', x=69.83, y=66.00, z=-88.55], EntityCreeper['Creeper'/296, l='MpServer', x=68.50, y=22.00, z=-53.50], EntityCreeper['Creeper'/297, l='MpServer', x=72.50, y=22.00, z=-50.50], EntitySkeleton['Skeleton'/298, l='MpServer', x=66.50, y=16.00, z=-52.50], EntitySkeleton['Skeleton'/299, l='MpServer', x=77.50, y=22.00, z=-50.50], EntityCreeper['Creeper'/171, l='MpServer', x=-24.53, y=13.97, z=-107.18], EntitySkeleton['Skeleton'/300, l='MpServer', x=77.50, y=22.00, z=-49.50], EntityZombie['Zombie'/172, l='MpServer', x=-18.50, y=33.00, z=-69.50], EntitySkeleton['Skeleton'/301, l='MpServer', x=76.50, y=20.00, z=-47.50], EntitySkeleton['Skeleton'/302, l='MpServer', x=75.50, y=19.00, z=-44.03], EntityRabbit['Rabbit'/303, l='MpServer', x=63.70, y=64.00, z=-43.34], EntityRabbit['Rabbit'/304, l='MpServer', x=66.97, y=66.00, z=-22.75], EntityBat['Bat'/305, l='MpServer', x=73.63, y=17.51, z=5.84], EntityCreeper['Creeper'/306, l='MpServer', x=76.50, y=52.00, z=6.50], EntityCreeper['Creeper'/180, l='MpServer', x=-0.50, y=14.00, z=-130.50], EntityCreeper['Creeper'/181, l='MpServer', x=-6.25, y=19.00, z=-96.50], EntitySquid['Squid'/182, l='MpServer', x=-3.09, y=58.00, z=-0.70], EntitySquid['Squid'/183, l='MpServer', x=-7.44, y=58.73, z=-2.35], EntityRabbit['Rabbit'/312, l='MpServer', x=92.10, y=76.00, z=-13.20], EntitySkeleton['Skeleton'/313, l='MpServer', x=87.49, y=47.97, z=12.74], EntityBat['Bat'/314, l='MpServer', x=80.32, y=39.30, z=-0.79], EntityBat['Bat'/322, l='MpServer', x=98.95, y=17.52, z=-58.08], EntityBat['Bat'/323, l='MpServer', x=102.64, y=17.47, z=-63.12], EntitySkeleton['Skeleton'/195, l='MpServer', x=0.50, y=14.00, z=-128.50], EntityBat['Bat'/324, l='MpServer', x=99.37, y=17.54, z=-17.33], EntitySkeleton['Skeleton'/196, l='MpServer', x=1.50, y=14.00, z=-125.50], EntityRabbit['Rabbit'/197, l='MpServer', x=13.53, y=65.00, z=-4.48], EntityZombie['Zombie'/325, l='MpServer', x=102.21, y=12.00, z=-1.50], EntitySkeleton['Skeleton'/326, l='MpServer', x=102.50, y=13.00, z=-4.50], EntitySkeleton['Skeleton'/327, l='MpServer', x=101.50, y=13.00, z=-3.50], EntityRabbit['Rabbit'/330, l='MpServer', x=123.51, y=68.00, z=-113.97], EntityRabbit['Rabbit'/331, l='MpServer', x=115.31, y=65.00, z=-51.07], EntityBat['Bat'/332, l='MpServer', x=124.49, y=18.10, z=-19.30], EntityEnderman['Enderman'/333, l='MpServer', x=113.50, y=43.00, z=-1.50], EntityCreeper['Creeper'/341, l='MpServer', x=131.45, y=19.00, z=-7.17], EntityCreeper['Creeper'/342, l='MpServer', x=132.50, y=18.00, z=-6.50], EntityCreeper['Creeper'/343, l='MpServer', x=131.75, y=18.00, z=-5.47], EntityEnderman['Enderman'/227, l='MpServer', x=16.69, y=22.00, z=-138.37], EntityRabbit['Rabbit'/228, l='MpServer', x=16.39, y=64.00, z=-104.25], EntityRabbit['Rabbit'/229, l='MpServer', x=19.60, y=64.00, z=-21.57], EntityXPOrb['Experience Orb'/357, l='MpServer', x=159.00, y=66.00, z=-93.67], EntityXPOrb['Experience Orb'/358, l='MpServer', x=157.39, y=67.00, z=-92.46], EntityCreeper['Creeper'/488, l='MpServer', x=96.50, y=13.00, z=-26.50], EntityCreeper['Creeper'/489, l='MpServer', x=95.66, y=13.00, z=-27.51], EntityCreeper['Creeper'/490, l='MpServer', x=94.50, y=13.00, z=-28.50], EntityRabbit['Rabbit'/253, l='MpServer', x=34.63, y=72.00, z=-1.96], EntityRabbit['Rabbit'/254, l='MpServer', x=42.11, y=71.00, z=-12.67], EntityRabbit['Rabbit'/255, l='MpServer', x=37.70, y=74.00, z=10.80]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2738)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.16.0-2-amd64
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4583502984 bytes (4371 MB) / 5368709120 bytes (5120 MB) up to 5368709120 bytes (5120 MB)
	JVM Flags: 10 total; -XX:+UseG1GC -Xmx5G -Xms5G -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:+AggressiveOpts -XX:+UseCompressedOops
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.4.2710 19 mods loaded, 19 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID               | Version         | Source                                 | Signature                                |
	|:--------- |:---------------- |:--------------- |:-------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft        | 1.12.2          | minecraft.jar                          | None                                     |
	| UCHIJAAAA | mcp              | 9.42            | minecraft.jar                          | None                                     |
	| UCHIJAAAA | FML              | 8.0.99.99       | forge-1.12.2-14.23.4.2710.jar          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge            | 14.23.4.2710    | forge-1.12.2-14.23.4.2710.jar          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | jei              | 4.10.0.198      | jei_1.12.2-4.10.0.198.jar              | None                                     |
	| UCHIJAAAA | appleskin        | 1.0.9           | AppleSkin-mc1.12-1.0.9.jar             | None                                     |
	| UCHIJAAAA | baubles          | 1.5.2           | Baubles-1.12-1.5.2.jar                 | None                                     |
	| UCHIJAAAA | ctm              | MC1.12-0.2.3.12 | CTM-MC1.12-0.2.3.12.jar                | None                                     |
	| UCHIJAAAA | diethopper       | 1.1             | diethopper-1.1.jar                     | None                                     |
	| UCHIJAAAA | mousetweaks      | 2.8             | MouseTweaks-2.8-mc1.12.1.jar           | None                                     |
	| UCHIJAAAA | nonvflash        | 1.2.0           | NoNVFlash-1.12.2-1.2.0.3-universal.jar | None                                     |
	| UCHIJAAAA | norecipebook     | 1.2.1           | noRecipeBook_v1.2.2formc1.12.2.jar     | None                                     |
	| UCHIJAAAA | placebo          | 1.4.0           | Placebo-1.12.2-1.4.0.jar               | None                                     |
	| UCHIJAAAA | snowaccumulation | 1.0.0           | SnowAccumulation-1.12-1.0.0.jar        | None                                     |
	| UCHIJAAAA | soundfilters     | 0.10_for_1.12   | SoundFilters-0.10_for_1.12.jar         | None                                     |
	| UCHIJAAAA | stg              | 1.12.2-1.2.3    | stg-1.12.2-1.2.3.jar                   | None                                     |
	| UCHIJAAAA | thaumcraft       | 6.1.BETA17      | Thaumcraft-1.12.2-6.1.BETA17.jar       | None                                     |
	| UCHIJAAAA | toastcontrol     | 1.7.0           | Toast+Control-1.12.2-1.7.0.jar         | None                                     |
	| UCHIJAAAA | unloader         | 1.2.0           | unloader-1.2.0.jar                     | None                                     |

	Loaded coremods (and transformers): 
F5FixLoadingPlugin (f5fix-1.1.jar)
  de.morrien.f5fix.F5FixTransformer
CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 390.48' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.4.2710
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 390.48, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x AMD Ryzen 5 1600 Six-Core Processor
```

**Comment by wamc2017** [comment] 2018-07-05 21:11
Dupe of #1095 
Should be fixed in beta 18 I guess, when it's released...

**Closed** 2018-07-18 09:31 UTC
Labels: bug, done, duplicate
