### ISSUE TITLE
Possible Issue with current thaumcraft (beta)

### ISSUE THREAD

**Issue by mandujib** [Azanor/thaumcraft-beta#1154] opened 2018-07-16 10:10 UTC
Current Version I have
1.12.2-6.1.BETA17.jar

Somehow, the essentia mirror and item mirrors are not rendering.
[https://imgur.com/a/sa1Z3HG](url)

**Comment by wamc2017** [comment] 2018-07-16 11:40
Dupe of #1088 

Seems an issue with newer forge versions...

**Closed** 2018-08-08 08:00 UTC
Labels: bug, duplicate
