### ISSUE TITLE
CTD with Beta 17

### ISSUE THREAD

**Issue by CloWnicide** [Azanor/thaumcraft-beta#1122] opened 2018-07-08 00:00 UTC
Minecraft Version: 1.12.2
Forge Version: 14.23.4.2729/14.23.4.2712
Mod Version: 6.1 Beta 17

Crash Report:

<details>
<summary> Click to expand </summary>
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b150.jar)
  LibLoader (# LibLoader.jar)
  LoadingPlugin (Quark-r1.4-123.jar)
  RandomPatches (randompatches-1.12.2-1.1.0.0.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9.1-1.12.2-anarchy.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  FMLPlugin (elulib-0.1.12.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.35.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  EECore (ExpandedEquivalence-1.12.2-4r.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-82.jar)
  CoreMod (TickProfiler-1.12-0.0.4.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  llibrary (llibrary-core-1.0.6-1.12.2.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
  SHLoadingPlugin (ScalingHealth-1.12-1.3.16-99.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.9.jar)
  AstralCore (astralsorcery-1.12.2-1.9.1.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  BedPatch (bedpatch-2.2-1.12.2.jar)
  HammerCoreCore (HammerCore-1.12.2-1.9.9.17.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  Plugin (NotEnoughIDs-1.5.4.2.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.1.9.jar)
  Wizardry Plugin (wizardry-0.8.5.jar)
  ISCore (ImprovableSkills_1.12.2-3.4.1r.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.4.0-80.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  DCLoadingPlugin (DummyCoreUnofficial-2.4.112.3.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.8-core.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 7/7/18 4:56 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thaumcraft (thaumcraft)
Caused by: java.lang.NullPointerException
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.getAspectsFromIngredients(ThaumcraftCraftingManager.java:531)
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromInfusionRecipes(ThaumcraftCraftingManager.java:439)
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromRecipes(ThaumcraftCraftingManager.java:563)
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:389)
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:355)
	at thaumcraft.common.lib.InternalMethodHandler.generateTags(InternalMethodHandler.java:91)
	at thaumcraft.api.aspects.AspectHelper.generateTags(AspectHelper.java:73)
	at thaumcraft.api.ThaumcraftApi.registerComplexObjectTag(ThaumcraftApi.java:337)
	at thaumcraft.common.config.ConfigAspects.registerItemAspects(ConfigAspects.java:424)
	at thaumcraft.common.config.ConfigAspects.postInit(ConfigAspects.java:29)
	at thaumcraft.proxies.CommonProxy.postInit(CommonProxy.java:82)
	at thaumcraft.proxies.ClientProxy.postInit(ClientProxy.java:53)
	at thaumcraft.Thaumcraft.postInit(Thaumcraft.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:330)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
</details>

**Comment by wamc2017** [comment] 2018-07-08 00:06
Looks like a dupe of #1087 
If you got Thaumic Additions installed, update it to 3r...

**Comment by CloWnicide** [comment] 2018-07-08 00:09
Having issues with Additions as well since the new version of Hammercore is causing my game to indefinitely stall while loading, but good to know that it is caused by that specific mod. Thank you.

**Closed** 2018-07-16 09:02 UTC
