### ISSUE TITLE
[1.12.2][B16]Thaumometer hard fps laggs

### ISSUE THREAD

**Issue by xILikepuddingx** [Azanor/thaumcraft-beta#1011] opened 2018-06-13 16:21 UTC
https://files.ilikepudding.de/v3zfag2kpy.mp4

Modpack: Modern Skyblock 3
Installed Mods additionally: Optifine
Forge: 2705

**Comment by Geethebluesky** [comment] 2018-06-13 18:07
Possible duplicate of #478. According to the author, there should be a fix in B17, which isn't out yet.

**Closed** 2018-07-04 11:22 UTC
Labels: bug, done, duplicate
