### ISSUE TITLE
[B15] crash on logging into server

### ISSUE THREAD

**Issue by DarcClan** [Azanor/thaumcraft-beta#875] opened 2018-05-25 11:22 UTC
java.lang.UnsupportedOperationException: null
	at java.util.concurrent.CopyOnWriteArrayList$COWIterator.remove(CopyOnWriteArrayList.java:1176) ~[?:1.8.0_25]
	at thaumcraft.client.fx.ParticleEngine.updateParticles(ParticleEngine.java:296) ~[ParticleEngine.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_251_ParticleEngine_updateParticles_ClientTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:343) ~[FMLCommonHandler.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1706) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[04:16:28] [main/INFO]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  AstralCore (astralsorcery-1.12.2-1.8.10.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.2-universal.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.13.jar)
  FMLPlugin (elulib-0.1.12.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-82.jar)
  LoadingPlugin (Quark-r1.4-123.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
  Plugin (NotEnoughIDs-1.5.4.2.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.22.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 5/25/18 4:16 AM
Description: Unexpected error

java.lang.UnsupportedOperationException
	at java.util.concurrent.CopyOnWriteArrayList$COWIterator.remove(CopyOnWriteArrayList.java:1176)
	at thaumcraft.client.fx.ParticleEngine.updateParticles(ParticleEngine.java:296)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_251_ParticleEngine_updateParticles_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:343)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1706)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by UnixRonin** [comment] 2018-05-25 12:29
Duplicate of #858

**Comment by Xules01** [comment] 2018-05-25 15:44
I'm getting this as well.  I have rolled back to beta13.  14 crashed my server and now with 15 the server seems stable, but the client crashes as soon as it connects to the server.

**Comment by UnixRonin** [comment] 2018-05-25 15:52
The client crashes as soon as Thaumcraft tries to render any particle, I think.

**Closed as completed** 2018-06-04 10:26 UTC
Labels: bug, duplicate, done
