### ISSUE TITLE
When go into magical forest, the game crashed.

### ISSUE THREAD

**Issue by sfchipan** [Azanor/thaumcraft-beta#811] opened 2018-05-20 12:37 UTC
Version: thaumcraft 6. 1.12.2 beta13
System: MacOS
Crash Report: https://paste.replaymod.com/xatamujene

**Comment by sfchipan** [comment] 2018-05-20 14:05
Got it. Crash with iChun's Hats mod.

**Comment by Geethebluesky** [comment] 2018-05-20 16:17
Duplicate of #416

**Closed** 2018-05-23 11:58 UTC
