### ISSUE TITLE
Thaumcraft plates

### ISSUE THREAD

**Issue by SingleTonne** [Azanor/thaumcraft-beta#1026] opened 2018-06-17 01:40 UTC
Can't seem to craft brass or thaumium plates. Currently have 1 ingot of brass (same with thaumium) in each of the middle row slots (horizontal line occupying the middle row) in the arcane workbench and nothing is craftable. Currently playing in the FTB revelation modpack with the addition of mekanism, mekanism tools and mekanism generators.

**Comment by Geethebluesky** [comment] 2018-06-17 01:49
The default TC recipe for plates is 3 ingots in a horizontal line, though. Does that work for you?

**Comment by Eruaph** [comment] 2018-06-21 13:17
This is almost certainly caused by the other mods in the FTB revelation pack, as it removes all the vanilla ways of making plates you have to use hammers/compactors/tinker's forge.

In FTB revelation you can make Thaumium plates with the compactor but you can't use the tinker's forge for some reason. This is inconsistent with the alchemical brass which can be melted in the tinker's forge and then have a plate made. So it would be nice if that could be fixed to be more consistent, I don't know if that can be fixed on the thaumcraft side though.

Ideally though it would be nice to have alternative thaumcraft ways to make plates so that you don't have to dip very far into other mods. For instance usually iron plates can be made with a hammer. Being able to convert directly from iron plates to thaumic/alchemical brass plates with the appropriate cauldron recipe would be convenient (even if you are playing thaumcraft stand alone).

**Closed** 2018-07-19 10:00 UTC
Labels: mod interaction, nothing to do
