### ISSUE TITLE
Old saves can't complete certain researches fully

### ISSUE THREAD

**Issue by Ulysses2** [Azanor/thaumcraft-beta#1213] opened 2018-07-27 23:33 UTC
In my world from one of the earlier betas, I have a couple of researches that are at the last stage (where they should be complete) but still marked as incomplete. Worse, this prevents me from completing a later research which has one as a prerequisite. It seems this happens when the player is in one of the middle stages of a research, but then everything after it is removed in an update, making it the final stage.

Here's a picture of the research in beta17, before the bug:  
![2018-07-27_19 15 19](https://user-images.githubusercontent.com/9127495/43350145-01d8d60a-91d3-11e8-94cb-faf28abe9669.png)

Here's a picture of the research in beta19, after the bug:  
![2018-07-27_19 19 37](https://user-images.githubusercontent.com/9127495/43350167-273e96d2-91d3-11e8-8cf8-7cc57af07fb7.png)

I can click on the research which depends on it and access its page:  
![2018-07-27_19 19 46](https://user-images.githubusercontent.com/9127495/43350201-67b95c9c-91d3-11e8-97e2-d38df4423bf1.png)

However, trying to complete it gets me stuck like this.  
![2018-07-27_19 19 22](https://user-images.githubusercontent.com/9127495/43350193-5aaf1b2c-91d3-11e8-8160-034590a322b7.png)

Another reseach seems to be bugged like the first one, but nothing appears to be locked off as a result.  
![2018-07-27_19 06 26](https://user-images.githubusercontent.com/9127495/43350271-d3328570-91d3-11e8-830b-ed6144b79f4c.png)

**Comment by enderger** [comment] 2018-07-28 18:34
Duplicate of #1187

**Closed** 2018-07-29 20:12 UTC
