### ISSUE TITLE
Crash problem with newer forge?

### ISSUE THREAD

**Issue by Senpaiducks** [Azanor/thaumcraft-beta#1474] opened 2018-10-05 10:52 UTC
Hiya,
for some reason when i try to start my Minecraft up beyond forge 14.23.4.2759 it seems to crash during the initialisation stage. Not 100% sure whats doing it (maybe incompatibilities with some of the mods named at the top of the crash report?) however i cannot see them causing issues with it.  Full crash report below.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-85.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.4.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 10/5/18 11:24 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thaumcraft (thaumcraft)
Caused by: java.lang.NoSuchFieldError: field_185200_c
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.getPotionReagentsRecursive(ThaumcraftCraftingManager.java:338)
	at thaumcraft.common.config.ConfigAspects.getPotionAspects(ConfigAspects.java:692)
	at thaumcraft.common.config.ConfigAspects.registerItemAspects(ConfigAspects.java:525)
	at thaumcraft.common.config.ConfigAspects.postInit(ConfigAspects.java:36)
	at thaumcraft.proxies.CommonProxy.postInit(CommonProxy.java:82)
	at thaumcraft.proxies.ClientProxy.postInit(ClientProxy.java:54)
	at thaumcraft.Thaumcraft.postInit(Thaumcraft.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1226197640 bytes (1169 MB) / 3844079616 bytes (3666 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2767 67 mods loaded, 67 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version                  | Source                                        | Signature                                |
	|:------ |:-------------------- |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJ  | minecraft            | 1.12.2                   | minecraft.jar                                 | None                                     |
	| UCHIJ  | mcp                  | 9.42                     | minecraft.jar                                 | None                                     |
	| UCHIJ  | FML                  | 8.0.99.99                | forge-1.12.2-14.23.4.2767.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ  | forge                | 14.23.4.2767             | forge-1.12.2-14.23.4.2767.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ  | opencomputers|core   | 1.7.2.67                 | minecraft.jar                                 | None                                     |
	| UCHIJ  | applecore            | 3.1.4                    | AppleCore-mc1.12.2-3.1.4.jar                  | None                                     |
	| UCHIJ  | jei                  | 4.12.1.217               | jei_1.12.2-4.12.1.217.jar                     | None                                     |
	| UCHIJ  | appleskin            | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                    | None                                     |
	| UCHIJ  | baubles              | 1.5.2                    | Baubles-1.12-1.5.2.jar                        | None                                     |
	| UCHIJ  | bdlib                | 1.14.3.12                | bdlib-1.14.3.12-mc1.12.2.jar                  | None                                     |
	| UCHIJ  | bibliocraft          | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar             | None                                     |
	| UCHIJ  | mantle               | 1.12-1.3.2.24            | Mantle-1.12-1.3.2.24.jar                      | None                                     |
	| UCHIJ  | natura               | 1.12.2-4.3.2.62          | natura-1.12.2-4.3.2.62.jar                    | None                                     |
	| UCHIJ  | forestry             | 5.8.1.322                | forestry_1.12.2-5.8.1.322.jar                 | None                                     |
	| UCHIJ  | binniecore           | 2.5.0.168                | binnie-mods-1.12.2-2.5.0.168.jar              | None                                     |
	| UCHIJ  | binniedesign         | 2.5.0.168                | binnie-mods-1.12.2-2.5.0.168.jar              | None                                     |
	| UCHIJ  | genetics             | 2.5.0.168                | binnie-mods-1.12.2-2.5.0.168.jar              | None                                     |
	| UCHIJ  | botany               | 2.5.0.168                | binnie-mods-1.12.2-2.5.0.168.jar              | None                                     |
	| UCHIJ  | extrabees            | 2.5.0.168                | binnie-mods-1.12.2-2.5.0.168.jar              | None                                     |
	| UCHIJ  | extratrees           | 2.5.0.168                | binnie-mods-1.12.2-2.5.0.168.jar              | None                                     |
	| UCHIJ  | biomesoplenty        | 7.0.1.2399               | BiomesOPlenty-1.12.2-7.0.1.2399-universal.jar | None                                     |
	| UCHIJ  | bookshelf            | 2.3.559                  | Bookshelf-1.12.2-2.3.559.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIEE | thaumcraft           | 6.1.BETA25               | Thaumcraft-1.12.2-6.1.BETA25.jar              | None                                     |
	| UCHI   | botania              | r1.10-356                | Botania r1.10-356.jar                         | None                                     |
	| UCHI   | chameleon            | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                      | None                                     |
	| UCHI   | ctm                  | MC1.12.2-0.3.2.18        | CTM-MC1.12.2-0.3.2.18.jar                     | None                                     |
	| UCHI   | chisel               | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                  | None                                     |
	| UCHI   | clienttweaks         | 3.1.9                    | ClientTweaks_1.12.2-3.1.9.jar                 | None                                     |
	| UCHI   | crafttweaker         | 4.1.10                   | CraftTweaker2-1.12-4.1.10.jar                 | None                                     |
	| UCHI   | twilightforest       | 3.8.689                  | twilightforest-1.12.2-3.8.689-universal.jar   | None                                     |
	| UCHI   | tconstruct           | 1.12.2-2.10.1.87         | TConstruct-1.12.2-2.10.1.87.jar               | None                                     |
	| UCHI   | conarm               | 1.1.2                    | conarm-1.12.2-1.1.2.jar                       | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCHI   | cookingforblockheads | 6.4.65                   | CookingForBlockheads_1.12.2-6.4.65.jar        | None                                     |
	| UCHI   | craftingtweaks       | 8.1.9                    | CraftingTweaks_1.12.2-8.1.9.jar               | None                                     |
	| UCHI   | ctgui                | 1.0.0                    | CraftTweaker2-1.12-4.1.10.jar                 | None                                     |
	| UCHI   | crafttweakerjei      | 2.0.2                    | CraftTweaker2-1.12-4.1.10.jar                 | None                                     |
	| UCHI   | embers               | 0.230                    | embers-0.230.jar                              | None                                     |
	| UCHI   | extrautils2          | 1.0                      | extrautils2-1.12-1.9.4.jar                    | None                                     |
	| UCHI   | gendustry            | 1.6.5.8                  | gendustry-1.6.5.8-mc1.12.2.jar                | None                                     |
	| UCHI   | gendustryjei         | 1.0.2                    | gendustryjei-1.0.2.jar                        | None                                     |
	| UCHI   | gravestone           | 1.10.1                   | gravestone-1.10.1.jar                         | None                                     |
	| UCHI   | waila                | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                   | None                                     |
	| UCHI   | inventorytweaks      | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHI   | ironbackpacks        | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar             | None                                     |
	| UCHI   | jeibees              | 0.9.0.5                  | jeibees-0.9.0.5-mc1.12.2.jar                  | None                                     |
	| UCHI   | journeymap           | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                   | None                                     |
	| UCHI   | magicbees            | 1.0                      | MagicBees-1.12.2-3.1.10.jar                   | None                                     |
	| UCHI   | refinedstorage       | 1.6.5                    | refinedstorage-1.6.5.jar                      | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| UCHI   | moartinkers          | 0.6.0                    | moartinkers-0.6.0.jar                         | None                                     |
	| UCHI   | mousetweaks          | 2.8                      | MouseTweaks-2.8-mc1.12.1.jar                  | None                                     |
	| UCHI   | opencomputers        | 1.7.2.67                 | OpenComputers-MC1.12.2-1.7.2.67.jar           | None                                     |
	| UCHI   | getalltheseeds       | 1.12a                    | Pam's Get all the Seeds! 1.12a.jar            | None                                     |
	| UCHI   | harvestcraft         | 1.12.2z                  | Pam's HarvestCraft 1.12.2z.jar                | None                                     |
	| UCHI   | refinedstorageaddons | 0.4.2                    | refinedstorageaddons-0.4.2.jar                | None                                     |
	| UCHI   | storagedrawers       | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.7.jar               | None                                     |
	| UCHI   | storagedrawersextra  | @VERSION@                | StorageDrawersExtras-1.12-3.1.0.jar           | None                                     |
	| UCHI   | taiga                | 1.3.2                    | taiga-1.12.2-1.3.2.jar                        | None                                     |
	| UCHI   | tc6aspects4jei       | 0.0.2a                   | tc6aspects4jei-0.0.2a.jar                     | None                                     |
	| UCHI   | thaumcomp            | 0.3.0.16                 | ThaumicComputers-MC1.12.2-0.3.0.16.jar        | None                                     |
	| UCHI   | thaumicjei           | 1.2.1                    | ThaumicJEI-1.12.2-1.5.3-20.jar                | None                                     |
	| UCHI   | thaumicperiphery     | 0.3.0                    | thaumicperiphery-0.3.0.jar                    | None                                     |
	| UCHI   | thaumictinkerer      | 1.12.2-5.0-353c71c       | thaumictinkerer-1.12.2-5.0-353c71c.jar        | None                                     |
	| UCHI   | tinkersoc            | 0.1                      | tinkersoc-0.4.jar                             | None                                     |
	| UCHI   | tinkertoolleveling   | 1.12.2-1.0.5.DEV.30c7957 | TinkerToolLeveling-1.12.2-1.0.5.jar           | None                                     |
	| UCHI   | wailaharvestability  | 1.1.12                   | WailaHarvestability-mc1.12-1.1.12.jar         | None                                     |
	| UCHI   | wawla                | 2.5.261                  | Wawla-1.12.2-2.5.261.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHI   | immersiveengineering | 0.12-85                  | ImmersiveEngineering-0.12-85.jar              | 4cb49fcde3b43048c9889e0a3d083225da926334 |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  team.chisel.ctm.client.asm.CTMTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-85.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
AppleCore (AppleCore-mc1.12.2-3.1.4.jar)
  squeek.applecore.asm.TransformerModuleHandler
TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  li.cil.oc.common.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 391.35' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	List of loaded APIs: 
		* AppleCoreAPI (3.1.0) from AppleCore-mc1.12.2-3.1.4.jar
		* Baubles|API (1.4.0.2) from Baubles-1.12-1.5.2.jar
		* BetterWithModsAPI (Beta 0.6) from AppleSkin-mc1.12-1.0.9.jar
		* BotaniaAPI (91) from Botania r1.10-356.jar
		* Chisel-API (0.0.1) from Chisel-MC1.12.2-0.2.1.35.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.12.2-0.2.1.35.jar
		* CraftingTweaks|API (4.1) from CraftingTweaks_1.12.2-8.1.9.jar
		* ctm-api (0.1.0) from CTM-MC1.12.2-0.3.2.18.jar
		* ctm-api-events (0.1.0) from CTM-MC1.12.2-0.3.2.18.jar
		* ctm-api-models (0.1.0) from CTM-MC1.12.2-0.3.2.18.jar
		* ctm-api-textures (0.1.0) from CTM-MC1.12.2-0.3.2.18.jar
		* ctm-api-utils (0.1.0) from CTM-MC1.12.2-0.3.2.18.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|arboriculture (4.3.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|book (5.8.1) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|climate (5.0.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|core (5.7.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|farming (5.8.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|food (1.1.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|genetics (5.7.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|greenhouse (5.2.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|gui (5.8.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|lepidopterology (1.4.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|modules (5.7.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|world (2.1.0) from forestry_1.12.2-5.8.1.322.jar
		* gendustryAPI (2.3.0) from gendustry-1.6.5.8-mc1.12.2.jar
		* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.12-85.jar
		* ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering-0.12-85.jar
		* journeymap|client-api (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-display (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-event (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-model (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-util (1.4) from journeymap-1.12.2-5.5.2.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.12.1.217.jar
		* MouseTweaks|API (1.0) from MouseTweaks-2.8-mc1.12.1.jar
		* opencomputersapi|component (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
		* opencomputersapi|core (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
		* opencomputersapi|driver (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
		* opencomputersapi|driver|item (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
		* opencomputersapi|event (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
		* opencomputersapi|filesystem (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
		* opencomputersapi|internal (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
		* opencomputersapi|machine (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
		* opencomputersapi|manual (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
		* opencomputersapi|network (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
		* opencomputersapi|prefab (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
		* StorageDrawersAPI (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* StorageDrawersAPI|event (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* StorageDrawersAPI|registry (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* StorageDrawersAPI|render (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* StorageDrawersAPI|storage (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* StorageDrawersAPI|storage-attribute (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* Thaumcraft|API (6.0.2) from Thaumcraft-1.12.2-6.1.BETA25.jar
		* WailaAPI (1.3) from Hwyla-1.8.26-B41_1.12.2.jar

**Comment by wamc2017** [comment] 2018-10-05 10:55
Dupe of #1468

**Closed** 2018-10-05 10:57 UTC
