### ISSUE TITLE
Thaumatorium not working on server

### ISSUE THREAD

**Issue by UxiT** [Azanor/thaumcraft-beta#1262] opened 2018-08-07 23:22 UTC
I made a thaumatoriam, added Nitor as heat source and when i put catalisator and click on recepies nothing happening. Just sound and nothing else

**Comment by wamc2017** [comment] 2018-08-08 01:31
Dupe of #1239

**Comment by UxiT** [comment] 2018-08-08 02:46
Does fix of this issue exist? Or what i have to do to fix that?

**Comment by davue** [comment] 2018-08-08 06:42
Wait until B21 gets released

**Closed** 2018-08-08 07:53 UTC
Labels: bug, done
