### ISSUE TITLE
crashed clicking on the caster guantlet bookmark

### ISSUE THREAD

**Issue by Teduce** [Azanor/thaumcraft-beta#558] opened 2018-04-28 14:45 UTC
here is the stack trace
running the beta11 build

Time: 4/28/18 7:42 AM
Description: Rendering screen

java.lang.ArrayIndexOutOfBoundsException: 1
	at thaumcraft.client.gui.GuiResearchPage.drawStackAt(GuiResearchPage.java:2035)
	at thaumcraft.client.gui.GuiResearchPage.drawArcaneCraftingPage(GuiResearchPage.java:1432)
	at thaumcraft.client.gui.GuiResearchPage.drawRecipe(GuiResearchPage.java:1037)
	at thaumcraft.client.gui.GuiResearchPage.drawPage(GuiResearchPage.java:465)
	at thaumcraft.client.gui.GuiResearchPage.genResearchBackground(GuiResearchPage.java:321)
	at thaumcraft.client.gui.GuiResearchPage.func_73863_a(GuiResearchPage.java:261)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by UnixRonin** [comment] 2018-04-28 15:32
Duplicate of #553

**Closed** 2018-05-04 12:13 UTC
Labels: duplicate, solved
