### ISSUE TITLE
Crash after entering the Nether.

### ISSUE THREAD

**Issue by Spyr4lW1z4rd** [Azanor/thaumcraft-beta#910] opened 2018-05-30 13:33 UTC
There seems to be a bug that causes minecraft to crash when entering the nether. this isn't an immediate crash, occurs after 3-5 seconds the first time, if you attempt to reload the world the crash is instantaneous. 

Mod List is Baubles-1.12-1.5.2 and Thaumcraft-1.12.2-6.1.BETA15.
Forge version is forge-1.12.2-14.23.4.2703
Operating system is Windows.

Edit: added crash report.
[crash-2018-05-31_20.13.53-client.txt](https://github.com/Azanor/thaumcraft-beta/files/2059717/crash-2018-05-31_20.13.53-client.txt)

**Comment by yunruiwatts** [comment] 2018-05-30 15:45
Can't tell for certain without a crashlog, but very likely a duplicate of #858

**Comment by Spyr4lW1z4rd** [comment] 2018-05-31 18:53
I don't think so. I have run several tests and the crash only occurs when you enter the nether, while #858 seems to be about some animations involving nitor (I may be wrong though).

**Comment by wamc2017** [comment] 2018-05-31 19:04
Does the crashlog say something about this?

`java.lang.UnsupportedOperationException
	at java.util.concurrent.CopyOnWriteArrayList$COWIterator.remove(Unknown Source)`

If so it's definitely a dupe of #858 because CopyOnWriteArray doesn't allow remove, which is used this way in the code... ^^

**Comment by Spyr4lW1z4rd** [comment] 2018-05-31 19:19
Yep, that line is in there. sorry for not including the crash report earlier, I've only just returned to minecraft after a long break.

**Closed** 2018-06-01 10:21 UTC
