### ISSUE TITLE
Crash when opening metallurgy research

### ISSUE THREAD

**Issue by Keltas** [Azanor/thaumcraft-beta#570] opened 2018-04-29 07:31 UTC
Using Thaumcraft 1.12-6.1.BETA11 on Forge 14.23.3.2676. The only other mods installed are Baubles 1.12-1.5.2 and JEI 1.12.2-4.9.1-172 .
To recreate, progress through Thaumcraft normally, unlock alchemy research tab, and in alchemy research tab click on Alchemical Metallurgy. The game proceeds to crash with following crash report:
https://pastebin.com/wYUbXTGY
The weird thing is that after restarting the game the tab is no longer crashing.
Here is the minecraft log in case it's needed:  https://pastebin.com/HreRH5LF

**Comment by Mike-U5** [comment] 2018-04-29 11:06
Were you by any change hovering over items in the recipe?
This sounds like it could be a duplicate of #519.

**Comment by Keltas** [comment] 2018-04-29 19:51
It is possible. I've checked it again while trying to not hover over anything in new world and the crash did not occur.

**Closed** 2018-05-04 12:13 UTC
Labels: duplicate, solved
