### ISSUE TITLE
Flux Condenser crashing upon entering an area

### ISSUE THREAD

**Issue by Rutes** [Azanor/thaumcraft-beta#1155] opened 2018-07-17 00:04 UTC
Going near a player's base on my server is causing clients to crash.

To quote the player: 

> must be the flux condenser i had
> its a block that when used with lattice, it reduced the amount of flux in the area to prevent the riftsI broke a lattice that was attatched to a clogged one (they clog) and poof

See crash log here:
https://gist.github.com/Rutes/011cbf5332c465dab3afc080b99e40a3

**Comment by Firestorme13** [comment] 2018-07-17 00:13
To add a little further detail: flux lattice was fine. I had one lattice on the condenser, then a second lattice on the first. That first got clogged, and I saw the second was sparking. I tried to break the sparking lattice and now cant approach my base without it "crashing whilst ticking block entity"

**Comment by Reassembly** [comment] 2018-07-17 05:54
Duplicate of #1095

**Closed** 2018-07-18 09:31 UTC
Labels: bug, done, duplicate
