### ISSUE TITLE
Potion Sprayer Duplicates Potions

### ISSUE THREAD

**Issue by Broam** [Azanor/thaumcraft-beta#375] opened 2018-03-01 05:05 UTC
Shift-clicking a potion puts the potion in the potion sprayer, but it also causes the potion to not leave my inventory (it appears to do so, but upon leaving the sprayer GUI, the potion drops in the world like when I exit a vanilla crafting table).

The potion sprayer still contains the original potion.

May be a cross-mod interaction, if you can't repro I'll post the mod list we're using.

**Comment by Azanor** [comment] 2018-03-01 06:45
Could you please post the mod list? I am unable to reproduce this.

**Comment by painquin** [comment] 2018-03-01 17:09
Broam's server admin here:

Baubles-1.10.2-1.3.13.jar
BiblioCraft[v2.2.5][MC1.10.2].jar
Chameleon-1.10.2-2.3.0.jar
Chisel-MC1.10.2-0.1.1.39.jar
CodeChickenCore-1.10.2-2.4.1.102-universal.jar
CodeChickenLib-1.10.2-2.5.9.320-universal.jar
CTM-MC1.10.2-0.2.3.26.jar
EnderStorage-1.10.2-2.2.1.106-universal.jar
gravestone-1.5.13.jar
Hwyla-1.8.17-B31_1.10.2.jar
jei_1.10.2-3.14.7.420.jar
journeymap-1.10.2-5.5.2.jar
Morpheus-1.10.2-3.1.13.jar
MouseTweaks-2.8-mc1.10.2.jar
NotEnoughItems-1.10.2-2.1.3.220-universal.jar
StorageDrawers-1.10.2-3.7.10.jar
Thaumcraft-1.10.2-6.0.BETA7.jar
ThaumicJEI-1.1.1.jar
WailaHarvestability-mc1.10.2-1.1.10.jar

**Comment by Broam** [comment] 2018-03-01 23:42
Verifying that that is the correct mod list.

**Comment by Broam** [comment] 2018-03-02 03:02
I've attempted to give you some more background [here](https://youtu.be/UUdxGLPoC8A).

If you need any more information, please ask.

**Comment by Z1xt** [comment] 2018-03-10 20:42
I can confirm that i can dupe potions in the same way. Playing "FTB Beyond" (It also has Mouse Tweaks) with Thaumcraft 6.0.BETA7.

**Comment by Azanor** [comment] 2018-04-11 07:57
This _should_ be fixed in the next release, but please reopen if it isn't

**Closed** 2018-04-17 12:26 UTC
Labels: bug, solved
