### ISSUE TITLE
Triple Meat Treats not craftable.

### ISSUE THREAD

**Issue by WhisperFire26** [Azanor/thaumcraft-beta#1165] opened 2018-07-18 21:05 UTC
I am using Thaumcraft 6 BETA 17 and I put a steak nugget, pork nugget, and a mutton nugget with sugar to attempt to make a stack of triple meat treats so that I can craft the verdant charm of sustaining and discovered that the triple meat treat is not craftable. I tried using the arcane worktable, vanilla crafting table, cyclic workbench, and my inventory and in the end I had to go into creative and trade the items in for a triple meat treat.

**Comment by wamc2017** [comment] 2018-07-18 22:44
Dupe of #697

**Closed** 2018-07-19 11:54 UTC
Labels: bug, done, duplicate
