### ISSUE TITLE
ThaumCraft 6 Beta 11 - unable to progress through alchemy research: essentia smelting stage 1/4

### ISSUE THREAD

**Issue by Ikarsu** [Azanor/thaumcraft-beta#555] opened 2018-04-28 05:39 UTC
Upon going through Alchemy research involving the crucible, I manage to run into a consumption task where the book asks for 6 vis crystal(s), but when hovering over, it does not tell which aspect it needs to complete the task. 

Lore/Thesis:
The player finds out how vis works and conducts tests involving "item destruction" to create vis crystals using quartz silver (quartz broken down into shards through shapeless crafting) as the catalyst to contain the aspects of vis. He/she thinks to him/herself that it would be best to start off with primal aspect vis crystals obtained through mining trips. 

Requirements (for stage 1): The book asks for 6 vis crystals, but does not define which of the 6 it requests when hovering over it. The lore states it would be best to have the 6 primal vis crystals in inventory.

Procedure(s)/attempted solutions: 
-have one crystal of each primal aspect in the hotbar. Nothing happens afterward, even when idling for a considerable amount of time and looking around the book for a submission offering.

-Threw the primal vis crystals into the crucible and waited about a minute for the book to process. Nothing happens, flux gas is produced, which subsequently caused an increased spawn rate of monsters around the underground mines.

-attempted to create complex vis crystals since the book does not define which kind of vis crystal it wants. Vis crystal of victus is created through throwing two seeds into the crucible and one quartz silver. Left over aspects are discarded, leaving flux gas and consequences as before mentioned above. Book does not accept the created vis crystal.

-attempted to contain the aspects through phials in the crucible, which can be stored/used later for crystal creation. Attempt has failed after throwing two pieces of dirt to produce 10 units of terra essentia and right clicking crucible with the phial yields no results. Essentia dissipates over time into flux gas, leading into consequences mentioned in attempt 2/3.

Analysis: 
-The book does not define which crystals it wants to consume and through being unable to define the aspect it wants, the player cannot progress through the stages contained within that research. It is possible for the game's codex to make/request an undefined vis crystal (called vis crystal in the JEI, but contains no aspects when hovered over), which cannot be obtained through any means in the game and subsequently breaking the progression of the mod itself. 
-When pressing view recipe for the undefined crystal using the JEI mod, it shows all the current aspects of TC 6 being made in a crucible with 2 aspect points creating 1 vis crystal using quartz silver as the catalyst (in the case for early alchemy tossing in items containing the aspect first, then tossing in the quartz silver).

**Comment by EnderofGames** [comment] 2018-04-28 06:14
Is your problem a duplicate of #511 and/or #546? 511 has a temporary solution.

**Comment by Ikarsu** [comment] 2018-04-28 20:36
looks like both cases are applied here. Looks like I'll wait for a future release that fixes the problem at hand. Didn't realized it was reported beforehand.

**Closed** 2018-05-04 12:13 UTC
Labels: duplicate, solved
