### ISSUE TITLE
Crash on Concurrent.CopyOnWriteArrayList 

### ISSUE THREAD

**Issue by davisjw** [Azanor/thaumcraft-beta#964] opened 2018-06-06 01:54 UTC
**---  Version Info  ---**
Java : 1.8.0_25
Minecraft : 1.12.2
Forge : 14.23.4.2707
Thaumcraft : 6.1.BETA15

**---  Recreation Steps  ---**
Load new SSP world,
Switch to creative,
Fly around until you hit a magical biome with a bunch of Thaumcraft trees
.. Game freezes for about 20s and then crashes 

**---  Stack Trace  ---**
```
Description: Unexpected error

java.lang.UnsupportedOperationException
	at java.util.concurrent.CopyOnWriteArrayList$COWIterator.remove(CopyOnWriteArrayList.java:1176)
	at thaumcraft.client.fx.ParticleEngine.updateParticles(ParticleEngine.java:296)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_161_ParticleEngine_updateParticles_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:343)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1706)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**---  Mod List  ---**
`micdoodlecore, bnbgamingcore, actuallyadditions, actuallybaubles, aether, antiqueatlas, applecore, appleskin, appliedenergistics2, armoreablemobs, aroma1997core, aromabackup, aromabackuprecovery, astikoor, autoreglib, badwithernocookiereloaded, base, baubles, bdlib, betterwithaddons, betteradvancements, betterwithmods, bibliocraft, bloodmoon, bnbgaminglib, bonsaitrees, bookshelf, botania, buildcraftbuilders, buildcraftcore, buildcraftenergy, buildcraftfactory, buildcraftlib, buildcraftrobotics, buildcraftsilicon, buildcrafttransport, caliper, ceanimals, ceramics, chameleon, chisel, chiselsandbits, clienttweaks, clumps, codechickenlib, cofhcore, cofhworld, colouredtooltips, commoncapabilities, compacter, compactmachines3, compactsolars, computercraft, contenttweaker, controlling, cookingforblockheads, extendedrenderer, coroutil, configmod, craftingtweaks, ctgui, crafttweaker, crafttweakerjei, ctm, cucumber, custommainmenu, cyclopscore, darkutils, death_compass, deathquotes, defaultoptions, dimensionalcontrol, dimstages, dirt2path, discordsuite, disenchanter, lootablebodies, dungpipe, emberroot, csb_ench_table, enderstorage, endertanks, extendedcrafting, farmingforblockheads, farseek, fastleafdecay, fastbench, fluxnetworks, forestry, microblockcbe, forgemultipartcbe, minecraftmultipartcbe, galacticraftplanets, galacticraftcore, galacticrafttweaker, gamestages, advgenerators, guideapi, hardcoredarkness, helpfixer, horsepower, huntingdim, waila, ichunutil, immcraft, immersivepetroleum, incontrol, ic2, industrialwires, integrateddynamics, integrateddynamicscompat, inventorytweaks, ironbackpacks, ironchest, itemstages, jei, jeibees, jeivillagers, journeymap, jmapstages, jeresources, kleeslabs, launchgui, loadingprofiler, lootbags, lttweaker, lucraftcore, magma_monsters, mantle, mcjtylib_ng, mcmultipart, mekanism, mekanismgenerators, mekanismtools, mercurius, minecolonies, minemenu, mtrm, mjrlegendslib, mob_grinding_utils, mobstages, modtweaker, modularrouters, morph, morpheus, mousetweaks, mpbasic, mputils, mrtjpcore, mtlib, multiblockstages, natura, neat, nex, norecipebook, nei, oeintegration, omlib, openmodularturrets, orbis_api, oretweaker, oreexcavation, orestages, p455w0rdslib, placebo, pneumaticcraft, portalgun, practicallogistics2, projectred-core, projectred-compat, projectred-fabrication, projectred-integration, projectred-transmission, projectred-illumination, projectred-expansion, projectred-relocation, projectred-transportation, projectred-exploration, quantumstorage, quark, realdrops, reborncore, recipestages, redstoneflux, refinedstorage, resourceloader, rftools, shetiphiancore, signals, signpost, sonarcore, soundfilters, stats_keeper, stevescarts, storagedrawers, streams, structuredcrafting, sync, tconstruct, terracore, thaumcraft, thaumicjei, theoneprobe, thermaldynamics, thermalexpansion, thermalfoundation, tinkersjei, tinkerstages, tinkertoolleveling, toastcontrol, topaddons, translocators, triumph, trumpetskeleton, ts2k16, vc, waterstrainer, witherskelefix, wrcbe, xnet, zombieawareness, immersiveengineering`

**Comment by wamc2017** [comment] 2018-06-06 02:18
Duplicate of #858 
Update to beta 16 and close this issue...

**Closed** 2018-06-06 09:37 UTC
