### ISSUE TITLE
Quartz Sliver doesn't interact with crucible 

### ISSUE THREAD

**Issue by dedinside** [Azanor/thaumcraft-beta#716] opened 2018-05-10 23:02 UTC
I'm stuck trying to condense essentia as i am unable to use the quartz slivers with the crucible. The correct essentia is in there but right clicking and throwing the quartz into the crucible has zero effect.

**Comment by dedinside** [comment] 2018-05-11 00:45
i was just trying to get some condensed potentia for a research it had 2 potentia and whatever ignis and i couldn't get either one out. I've tried click it all over and throwing it in to no avail. the crucible wont even absorb it if i just toss it in

**Comment by Geethebluesky** [comment] 2018-05-11 01:52
You have your Goggles on and you're seeing the amounts left in the crucible right?

**Comment by Natesky9** [comment] 2018-05-14 08:43
could be a duplicate of #739, make sure you've opened that page in your thaumonomicon to "unlock" the recipe. Even though you know the recipe, the page has to unlock it for you-- no shortcuts
Also, try clicking on the top side of the crucible with the slivers

**Closed** 2018-07-19 12:29 UTC
