### ISSUE TITLE
[BETA 4] Game crash when looking mod on JEI

### ISSUE THREAD

**Issue by serialtasted** [Azanor/thaumcraft-beta#263] opened 2018-02-12 01:07 UTC
Hello there,
My game is crashing when I try to search for "@thaumcraft" on JEI it the following crash log:

> ---- Minecraft Crash Report ----
> 
> WARNING: coremods are present:
>   CorePlugin (MrTJPCore-1.10.2-2.0.1.20-universal.jar)
>   LoadingPlugin (HardcoreDarkness-MC1.10.2-1.9.jar)
>   MalisisCorePlugin (malisiscore-1.10.2-4.4.0.jar)
>   literalascension (literalascension-1.10.2-1.0.2.2.jar)
>   EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
>   AppEngLoadingPlugin (appliedenergistics2-rv4-stable-1.jar)
>   IC2core (industrialcraft-2-2.6.252-ex110.jar)
>   BetterFoliageLoader (BetterFoliage-MC1.10.2-2.1.11.jar)
>   AppleCore (AppleCore-mc1.10.2-3.1.0.jar)
>   TANLoadingPlugin (ToughAsNails-1.9.4-1.1.1.66-universal.jar)
>   RBLoadingPlugin (RealBench-1.10.2-1.3.2.jar)
>   HammerCoreCore (HammerCore-1.10.2-1.9.4.3.jar)
>   RebornCoreASM (RebornCore-1.10.2-2.13.6.142-universal.jar)
>   FMLPlugin (InventoryTweaks-1.61-58.jar)
>   AdvancedRocketryPlugin (AdvancedRocketry-1.10.2-1.2.5a.jar)
>   ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.11.jar)
>   CoFH Loading Plugin (CoFHCore-1.10.2-4.1.12.17-universal.jar)
>   Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (FoamFix-1.11.2-0.7.3-Anarchy.jar)
>   llibrary (llibrary-1.7.7-1.10.2.jar)
>   RefinedFixerLoadingPlugin (ImmersiveCables-1.10.2-1.2.1.jar)
>   CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.320-universal.jar)
>   DummyPlugin (ForgeEndertech-1.10.2-1.3.4.0-build.0057.jar)
>   ForgelinPlugin (Forgelin-1.6.0.jar)
>   LoadingPlugin (Quark-r1.1-70.jar)
>   SHLoadingPlugin (ScalingHealth-1.12-1.2.2-70.jar)
>   IvToolkit (IvToolkit-1.3.3-1.10.jar)
>   CXLibraryCore (cxlibrary-1.10.2-1.2.4.jar)
>   TransformerLoader (OpenComputers-MC1.10.2-1.7.1.150.jar)
>   Plugin (NotEnoughIDs-1.5.3.1.jar)
>   CTMCorePlugin (CTM-MC1.10.2-0.2.3.26.jar)
>   DynamicSurroundingsCore (DynamicSurroundings-1.10.2-3.4.9.3.jar)
> Contact their authors BEFORE contacting forge
> 
> // Would you like a cupcake?
> 
> Time: 2/12/18 1:04 AM
> Description: Rendering ingredient
> 
> java.lang.NullPointerException: Rendering ingredient
> 	at thaumcraft.common.items.casters.ItemFocus.getFocusColors(ItemFocus.java:42)
> 	at thaumcraft.client.ColorHandler.lambda$registerItemColourHandlers$11(ColorHandler.java:183)
> 	at net.minecraft.client.renderer.color.ItemColors.func_186728_a(ItemColors.java:139)
> 	at net.minecraft.client.renderer.RenderItem.func_175032_a(RenderItem.java:217)
> 	at net.minecraft.client.renderer.RenderItem.func_175045_a(RenderItem.java:131)
> 	at net.minecraft.client.renderer.RenderItem.func_175036_a(RenderItem.java:112)
> 	at mezz.jei.gui.ingredients.GuiIngredientFast.renderItemAndEffectIntoGUI(GuiIngredientFast.java:125)
> 	at mezz.jei.gui.ingredients.GuiIngredientFast.renderItemAndEffectIntoGUI(GuiIngredientFast.java:97)
> 	at mezz.jei.gui.ingredients.GuiIngredientFastList.render(GuiIngredientFastList.java:164)
> 	at mezz.jei.gui.ItemListOverlayInternal.drawScreen(ItemListOverlayInternal.java:305)
> 	at mezz.jei.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:89)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1801_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
> 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
> 	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:590)
> 	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:73)
> 	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
> 	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:591)
> 	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
> 	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
> 	at net.minecraft.client.main.Main.main(SourceFile:124)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by taggedjc** [comment] 2018-02-12 04:14
This seems to be a duplicate of the problem in [this bug](https://github.com/Azanor/thaumcraft-beta/issues/248).

**Comment by MainFreak** [comment] 2018-02-14 08:38
It is indeed.

**Closed** 2018-02-15 10:16 UTC
Labels: bug, done, duplicate
