### ISSUE TITLE
Thaumatorium recipe for spiritus crystals is missing

### ISSUE THREAD

**Issue by lOmicronl** [Azanor/thaumcraft-beta#1445] opened 2018-09-25 20:35 UTC
(Beta 24) The teeny-tiniest of bugs. A _sliver_ of a bug, if you will =P

Upon inserting a quartz sliver into the thaumatorium, it offers you 36 different crystal recipes - one for each aspect. Except, there are 37 aspects in Thaumcraft. Spiritus is missing in the recipe list of the thaumatorium, so you cannot use it to convert spiritus essentia into crystals.

Not like it's difficult to just use a crucible instead, but for completeness' sake...

**Comment by wamc2017** [comment] 2018-09-25 22:57
Dupe of #1260

**Closed** 2018-09-26 06:38 UTC
Labels: bug, done, duplicate
