### ISSUE TITLE
crashes client when searching for scribing tools in JEI

### ISSUE THREAD

**Issue by Spenny519** [Azanor/thaumcraft-beta#253] opened 2018-02-10 05:31 UTC
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.61-58.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 2/8/18 9:53 AM
Description: Rendering ingredient

java.lang.NullPointerException: Rendering ingredient
	at thaumcraft.common.items.casters.ItemFocus.getFocusColors(ItemFocus.java:42)
	at thaumcraft.client.ColorHandler.lambda$registerItemColourHandlers$11(ColorHandler.java:183)
	at thaumcraft.client.ColorHandler$$Lambda$15/1507561086.func_186726_a(Unknown Source)
	at net.minecraft.client.renderer.color.ItemColors.func_186728_a(ItemColors.java:139)
	at net.minecraft.client.renderer.RenderItem.func_175032_a(RenderItem.java:217)
	at net.minecraft.client.renderer.RenderItem.func_175045_a(RenderItem.java:131)
	at net.minecraft.client.renderer.RenderItem.func_175036_a(RenderItem.java:112)
	at mezz.jei.gui.ingredients.GuiIngredientFast.renderItemAndEffectIntoGUI(GuiIngredientFast.java:125)
	at mezz.jei.gui.ingredients.GuiIngredientFast.renderItemAndEffectIntoGUI(GuiIngredientFast.java:97)
	at mezz.jei.gui.ingredients.GuiIngredientFastList.render(GuiIngredientFastList.java:164)
	at mezz.jei.gui.ItemListOverlayInternal.drawScreen(ItemListOverlayInternal.java:305)
	at mezz.jei.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:89)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_96_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:590)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:73)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:591)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at thaumcraft.common.items.casters.ItemFocus.getFocusColors(ItemFocus.java:42)
	at thaumcraft.client.ColorHandler.lambda$registerItemColourHandlers$11(ColorHandler.java:183)
	at thaumcraft.client.ColorHandler$$Lambda$15/1507561086.func_186726_a(Unknown Source)
	at net.minecraft.client.renderer.color.ItemColors.func_186728_a(ItemColors.java:139)
	at net.minecraft.client.renderer.RenderItem.func_175032_a(RenderItem.java:217)
	at net.minecraft.client.renderer.RenderItem.func_175045_a(RenderItem.java:131)
	at net.minecraft.client.renderer.RenderItem.func_175036_a(RenderItem.java:112)

-- Ingredient being rendered --
Details:
	Ingredient Mod: Thaumcraft
	Ingredient Info: 1xitem.focus@0 thaumcraft:focus nbt:{core:{}}
Stacktrace:
	at mezz.jei.gui.ingredients.GuiIngredientFast.createRenderIngredientException(GuiIngredientFast.java:370)
	at mezz.jei.gui.ingredients.GuiIngredientFast.renderItemAndEffectIntoGUI(GuiIngredientFast.java:99)
	at mezz.jei.gui.ingredients.GuiIngredientFastList.render(GuiIngredientFastList.java:164)
	at mezz.jei.gui.ItemListOverlayInternal.drawScreen(ItemListOverlayInternal.java:305)
	at mezz.jei.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:89)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_96_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:590)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:73)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:591)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
	Mouse location: Scaled: (381, 249). Absolute: (1524, 81)
	Screen size: Scaled: (480, 270). Absolute: (1920, 1080). Scale factor of 4

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Guatemala__koala'/24, l='MpServer', x=655.73, y=4.00, z=893.88]]
	Chunk stats: MultiplayerChunkCache: 121, 121
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (666,4,887), Chunk: (at 10,0,7 in 41,55; contains blocks 656,0,880 to 671,255,895), Region: (1,1; contains chunks 32,32 to 63,63, blocks 512,0,512 to 1023,255,1023)
	Level time: 19305 game time, 4144 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 32 total; [EntityVillager['Villager'/2, l='MpServer', x=616.59, y=4.00, z=848.72], EntityVillager['Villager'/3, l='MpServer', x=627.65, y=4.00, z=873.62], EntityVillager['Villager'/4, l='MpServer', x=636.49, y=4.00, z=858.71], EntityVillager['Villager'/5, l='MpServer', x=661.48, y=3.94, z=866.43], EntityVillager['Villager'/6, l='MpServer', x=634.30, y=7.00, z=871.30], EntityVillager['Villager'/7, l='MpServer', x=636.70, y=5.00, z=877.70], EntityVillager['Villager'/8, l='MpServer', x=629.30, y=3.94, z=853.50], EntityVillager['Villager'/9, l='MpServer', x=633.06, y=5.00, z=857.43], EntityVillager['Villager'/10, l='MpServer', x=642.70, y=3.94, z=853.47], EntityVillager['Villager'/11, l='MpServer', x=636.70, y=7.00, z=871.30], EntityVillager['Villager'/12, l='MpServer', x=656.02, y=4.00, z=838.70], EntityVillager['Villager'/13, l='MpServer', x=650.50, y=4.00, z=859.44], EntityVillager['Villager'/14, l='MpServer', x=661.48, y=3.94, z=833.11], EntityVillager['Villager'/15, l='MpServer', x=637.50, y=5.00, z=846.64], EntityVillager['Villager'/16, l='MpServer', x=663.41, y=5.00, z=850.43], EntityCow['Cow'/71313, l='MpServer', x=652.16, y=4.00, z=946.14], EntityVillager['Villager'/18, l='MpServer', x=657.48, y=5.00, z=842.44], EntityCow['Cow'/71315, l='MpServer', x=641.87, y=4.00, z=934.79], EntityVillager['Villager'/19, l='MpServer', x=663.53, y=5.00, z=836.50], EntityCow['Cow'/71314, l='MpServer', x=652.19, y=4.00, z=941.77], EntityVillager['Villager'/20, l='MpServer', x=635.50, y=6.00, z=872.70], EntityVillager['Villager'/21, l='MpServer', x=655.29, y=4.00, z=849.68], EntityCow['Cow'/71316, l='MpServer', x=655.20, y=4.00, z=948.55], EntityVillager['Villager'/22, l='MpServer', x=635.60, y=4.00, z=858.28], EntityVillager['Villager'/23, l='MpServer', x=656.72, y=5.00, z=840.30], EntityChicken['Chicken'/71318, l='MpServer', x=670.28, y=4.00, z=957.57], EntitySheep['Sheep'/71273, l='MpServer', x=605.50, y=4.00, z=943.50], EntityPlayerSP['Guatemala__koala'/24, l='MpServer', x=655.73, y=4.00, z=893.88], EntitySheep['Sheep'/71272, l='MpServer', x=593.74, y=4.00, z=938.61], EntityPig['Pig'/71275, l='MpServer', x=608.50, y=4.00, z=937.50], EntityPig['Pig'/71274, l='MpServer', x=607.50, y=4.00, z=937.50], EntityItem['item.item.egg'/1355756, l='MpServer', x=671.21, y=4.00, z=956.67]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2135475160 bytes (2036 MB) / 2847932416 bytes (2716 MB) up to 7158628352 bytes (6827 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx7680m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2511 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2511.jar) 
	UCHIJAAAA	Forge{12.18.3.2511} [Minecraft Forge] (forge-1.10.2-12.18.3.2511.jar) 
	UCHIJAAAA	Baubles{1.3.13} [Baubles] (Baubles-1.10.2-1.3.13.jar) 
	UCHIJAAAA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJAAAA	JEI{3.14.7.420} [Just Enough Items] (jei_1.10.2-3.14.7.420.jar) 
	UCHIJAAAA	thaumcraft{6.0.BETA4} [Thaumcraft] (Thaumcraft-1.10.2-6.0.BETA4.jar) 
	Loaded coremods (and transformers): 
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 22.20.16.4836' Renderer: 'Intel(R) HD Graphics 615'
	Launched Version: forge-12.18.3.2511
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 615 GL version 4.5.0 - Build 22.20.16.4836, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i7-7Y75 CPU @ 1.30GHz

**Comment by XoviaHarmile** [comment] 2018-02-10 05:33
Same thing happens when typing 'fo', though I assume this has something to do with the problems making foci rather than your problem.

**Comment by PHCLMicoTW** [comment] 2018-02-10 13:09
Same problem on 1.10.2-BETA4 but work fine in 1.10.2-BETA3 (only test JEI searching with 51 mods activated).

**Comment by Goof245** [comment] 2018-02-10 14:28
Same crash as the existing 2-3 reports regarding JEI + gauntlet Foci....

https://github.com/Azanor/thaumcraft-beta/issues/248 https://github.com/Azanor/thaumcraft-beta/issues/229 https://github.com/Azanor/thaumcraft-beta/issues/241

**Comment by iopredman** [comment] 2018-02-11 02:36
This issue has been reproduced by myself with version 4 of the beta and the latest (2/10/18) version of JEI. I was unable to specifically figure out which item causes the crash. On my all the mods server, however, the issue was caused by attempting to type "see" which may be a clue.

**Comment by kd8lvt** [comment] 2018-02-11 17:04
This is a bug that has been known for a while. Foci rendering is broken in your inventory. So, to avoid this issue, avoid searching for things that might be in any foci's tooltip. For example;
    Looking for a **fo**rtune book? Search "ortune" instead of "Fortune"
    Looking for **Terra** Vis Crystals? Search "Crystal" instead of "Terra"
    Looking for Scribing Tools? Search "Tools" instead
This error has been fixed in B5, according to Azanor in this report: 237

**Closed** 2018-02-14 06:55 UTC
Labels: bug, done, duplicate
