### ISSUE TITLE
mossy stone not working

### ISSUE THREAD

**Issue by flamingram** [Azanor/thaumcraft-beta#584] opened 2018-04-30 04:40 UTC
so i got some mossy stone but its not working i really need to finish to get everfull urn its tuck on hedge alchemy

**Comment by Alaberti** [comment] 2018-04-30 04:45
https://minecraft.gamepedia.com/Moss_Stone#Crafting_ingredient

**Comment by flamingram** [comment] 2018-04-30 04:47
what is teh comman to cheat it in because ive done /tc research username and hedge_alechmy still wotn cheat in

**Comment by wamc2017** [comment] 2018-04-30 11:44
Dupe of #510 #548.

The research name is HEDGEALCHEMY, you could list the names with /tc research list...

**Comment by AnrDaemon** [comment] 2018-04-30 12:34
#511 has a temp. fix.

**Closed** 2018-05-04 12:13 UTC
Labels: bug, solved
