### ISSUE TITLE
[B12] Certain blocks from Millenaire causes server crash when taint tries to spread to them.

### ISSUE THREAD

**Issue by ohzee00** [Azanor/thaumcraft-beta#658] opened 2018-05-07 01:13 UTC
(This is my first ever issue report so apologies if I mess up at all)

Here is the crash long:
[crash-2018-05-06_19.43.09-server.txt](https://github.com/Azanor/thaumcraft-beta/files/1978194/crash-2018-05-06_19.43.09-server.txt)
But the main line is this: 

`java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=half, clazz=class net.minecraft.block.BlockSlab$EnumBlockHalf, values=[top, bottom]} as it does not exist in BlockStateContainer{block=millenaire:pathslabs, properties=[stable, variant]}`

Which it seems like the taint block is trying to spread to one of the slabs yet can't get if it is either top or bottom cause the Millenaire slab does not specify.

**Comment by Azanor** [comment] 2018-05-07 06:49
While I am sure taint triggers this bug, it is not directly the cause. I simply try and replace those blocks using normal minecraft methods. I suspect those methods are running into issue with those slabs - or at least blocks it thinks are slabs and then causes all kinds of derpiness. You might want to report this to the Millenaire dev and reference this issue. 
It should probably be fixed on his side, but I will keep this open should that not be the case.

**Comment by ohzee00** [comment] 2018-05-07 07:46
Alright thanks for the input, just sent a issue on their Gitlab thing.
Here's the link if you want it: https://gitlab.com/Millenaire/Public/issues/203

**Comment by ohzee00** [comment] 2018-05-07 11:15
Alright the dev for Millenaire responded and said they'll take care of it, so I guess this should be marked as solved?

**Closed** 2018-05-07 11:15 UTC
Labels: possible bug, question
