### ISSUE TITLE
[B16] Linked mirrors stack with unlinked; general mirror confusion

### ISSUE THREAD

**Issue by Geethebluesky** [Azanor/thaumcraft-beta#971] opened 2018-06-06 17:08 UTC
While I was experimenting in previous betas I ended up making 3 Essentia mirrors. I have all 3 in my inventory now; two are linked.

Which ones, though?

![image](https://user-images.githubusercontent.com/1903792/41053634-609dfbb6-6979-11e8-873c-171518ff3129.png)

Seems to me there's a bug currently allowing 1 of a linked pair to stack with another unlinked mirror. I had placed what I thought was the "extra" mirror in a chest, only to find it was actually the linked one which had lost its linked texture (or never had it, as becomes apparent in the comment below). Since the mirrors don't allow relinking while they both exist, the only way to be 100% sure which 2 are linked is to scrap all of them and recreate, it seems...

To avoid this, would it be possible for mirrors to show their linked coordinates _while they're being looked at_ (via JEI for example)? Not sure if this is a request for you or the author of Thaumic JEI though.

And could **both** mirrors show coordinates while we hover over them in the inventory? Currently I've only been able to see coordinates for one of the pair.

**Comment by Geethebluesky** [comment] 2018-06-06 17:33
More info if it helps...

![image](https://user-images.githubusercontent.com/1903792/41054733-70c80a6a-697c-11e8-8dd9-b8c152984c6a.png)

In the pic above, I placed a new mirror on the ceiling (after smelting the other 3). Clicked on it with another new mirror. The one I'm holding has acquired coordinates, and the black "linked mirror in inventory" texture. The one on the ceiling still looks unlinked though, has the regular mirror texture.

![image](https://user-images.githubusercontent.com/1903792/41054804-a4fe6c02-697c-11e8-9112-69498a4c813b.png)
Only the mirror I clicked with has the linked texture in inventory as well, and the other one shows no indication of being linked at all.

Now If I remove the apparently unlinked one, place the one I previously clicked with on the wall instead, and click with the one that looks unlinked, Thaumcraft tells me "yeah it's already linked", finally. 

![image](https://user-images.githubusercontent.com/1903792/41055005-4d866938-697d-11e8-99b9-ef61beed7b90.png)


But it doesn't tell me it's linked to the one in my hand. So if I made a third or a fourth mirror above? I have to guess.

I think this is really user-unfriendly because you have to fiddle around with both mirrors to figure that out. 



IMO **both** mirrors should acquire the linked textures and display coordinates as soon as they're paired to avoid the issue above.

**Comment by apmax** [comment] 2018-06-06 20:40
IIRC the linked texture should appear on both when they have both been placed down, and the problem you're experiencing is related to the situation where picking up one mirror before placing it's linked partner causes odd behavior, correct?

**Comment by Geethebluesky** [comment] 2018-06-06 23:10
I placed the first (new, never linked) mirror next to my essentia jars, clicked on it with the other (new) mirror, and the first image above occurred.  I didn't move the first mirror before trying to link.

**Comment by apmax** [comment] 2018-06-06 23:28
In my experience, both mirrors need to be placed in the world at the same time to be and remain properly linked.  If you place a mirror on the ground and use another mirror on it, you have to then place that mirror in the world for the link to work between them.

**Comment by Geethebluesky** [comment] 2018-06-07 01:37
Sorry but what you're saying is not clear at all.

> at the same time

Not always possible: my altar is about 100 blocks away. That's why I place the first mirror in the world, click it with the second mirror, then go place the second mirror.

>  If you place a mirror on the ground and use another mirror on it, you have to then place that mirror in the world for the link to work between them.

And that's exactly what I did.

**Comment by apmax** [comment] 2018-06-07 01:52
Place your mirror.  Right click using another mirror.  Go and place that mirror.  Then the mirrors should be set up correctly.  
I'm trying to reproduce your issue but I'm not encountering any problem with mirror stacking.  The only somewhat related situation I've found is: if you have two paired mirrors in the world, you can break one and place it elsewhere without breaking the link. Because of this, if you break one mirror and then break the other, the first will still show itself to be linked and the other will return to being just a standard, stackable mirror.  This can be fixed by placing and re-breaking the first, still-linked mirror.  I've had no issues linking, relinking, unlinking, and relocating mirrors. 
Do you have a more consistent way to replicate this bug you're experiencing?

**Comment by Geethebluesky** [comment] 2018-06-07 01:57
> Do you have a more consistent way to replicate this bug you're experiencing?

Nope, it's really just the steps I gave above in the images:

1. Create both mirrors.
2. Place one in the world (no. 1)
3. Click on no. 1 with no. 2: notice the texture for no.1 **does not** change (at least that's what happened to me, which I find abnormal)
4. Take no. 1 off the wall, place no. 2 in its place
5. Place no. 1 somewhere else: I would expect them to still work, but they don't, which I also consider undesirable behavior.

The reason why I'm saying it's a problem is because it feels way more logical to let players move both mirrors wherever they choose, but that doesn't seem possible at the moment...

**Comment by apmax** [comment] 2018-06-07 02:20
For what purpose are you breaking the first mirror before you place down the second?  You're breaking it before a link has been established.  In order for a link to be completely established between mirrors, it seems that they have to both be present in the world at the same time, and once you have mirrors in that state, you can only move one at a time, as breaking both of them will cancel the link.  
Until you actually have both mirrors placed down, the one without the hole in it is just a plain unlinked mirror.  The one in your inventory with the black spot on it is simply marking where it's partner can be found, so that it can form a link once placed in the world.  If a mirror is not present on a block in the world, it cannot be linked to.

Following your results, no linked mirrors stack with unlinked mirrors at all.  If I start with 3 unlinked mirrors, I end up with 2 unlinked mirrors and one mirror storing the coordinates of empty air, which can be fixed by simply placing and breaking it again.

**Comment by Geethebluesky** [comment] 2018-06-07 04:35
> Following your results, no linked mirrors stack with unlinked mirrors at all.

Well I've shown that it does happen for me, so there's still a problem.

**Comment by apmax** [comment] 2018-06-07 04:55
I don't think your problem with the mirrors isn't an actual issue with the mirrors themselves, and moreso with your understanding of their function.
The actual mirror items do not "link" to eachother in your inventory.  When you right click on a placed mirror with one in your hand, you're telling the mirror in your hand where in your world it should search to find a partner to exchange items with when placed down.  That is what the change in texture means, the mirror has coordinates saved.  If you destroy the mirror already at those coordinates, you are preventing a link from forming.  When you place the mirror with the coordinate information down, it will look at those coordinates, see that there is no mirror there, and revert to being a regular unlinked mirror. The mirror on the wall does not become physically connected to the mirror in your inventory until both of them have been placed down and allowed to communicate with eachother, which is why when you break it before that happens, it stacks with the rest of the unlinked mirrors in your inventory.  It has no linking information at all.
This functionality is not fiddly nor temperamental at all, it's straightforward and very much deterministic.

**Comment by Azanor** [comment] 2018-06-07 06:49
Yup - what you are experiencing is not a bug. You are not really linking two mirrors - you are linking one mirror in your inventory with another already placed mirrors location and if you remove the placed mirror it means there is no longer a link.
Secondly I have no control over what stacks and what doesn't - that is is part of MC itself. As long as their internal nbt data differs mirrors will not stack - if they do stack it means you either linked multiple mirrors somehow or they are not linked at all.

**Closed by Azanor** 2018-06-07 06:49 UTC
