### ISSUE TITLE
Golem use seal doesn't seem to work with Astral Sorcery lightwell

### ISSUE THREAD

**Issue by drachs** [Azanor/thaumcraft-beta#990] opened 2018-06-08 20:52 UTC
I thought it would be neat to use a golem instead of a mechanical user.  You have to right click the lightwell with a gem like aquamarine to put it in.  The golem fetches the gem from the chest fine and starts clicking but it doesn't get put into the well.

**Comment by wamc2017** [comment] 2018-06-09 01:50
Do you have FTBUtilities installed? If so it could be a duplicate of #956

**Closed** 2018-07-19 10:22 UTC
Labels: mod interaction, nothing to do
