### ISSUE TITLE
Nitro crash caused by placeing a nitro into the map

### ISSUE THREAD

**Issue by mingl0280** [Azanor/thaumcraft-beta#882] opened 2018-05-26 04:25 UTC
Version: 1.12 beta 15
Seems like someting in the ParticleEngine went wrong.
This crashes the whole map while you tries to put a nitro to the map - server doesn't crash. So this literally causing only client side crash. The nitro is successfully placed in the map in multiplayer mode, so the result would be anyone trying to load that chunk will crash their own client.

Crash log:
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  CorePlugin (SmoothFont-1.12.2-1.12-b1.jar)
  CoreModLoader (Sound-Physics-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 5/25/18 10:18 PM
Description: Unexpected error

java.lang.UnsupportedOperationException
	at java.util.concurrent.CopyOnWriteArrayList$COWIterator.remove(Unknown Source)
	at thaumcraft.client.fx.ParticleEngine.updateParticles(ParticleEngine.java:296)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_102_ParticleEngine_updateParticles_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:343)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1706)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.concurrent.CopyOnWriteArrayList$COWIterator.remove(Unknown Source)
	at thaumcraft.client.fx.ParticleEngine.updateParticles(ParticleEngine.java:296)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_102_ParticleEngine_updateParticles_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:343)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['_Ming'/2253, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Chunk stats: MultiplayerChunkCache: 122, 122
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 23 game time, 23 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 52 total; [EntityPlayerSP['_Ming'/2253, l='MpServer', x=8.50, y=65.00, z=8.50], EntityEnderman['末影人'/1536, l='MpServer', x=223.50, y=64.00, z=321.50], EntityChicken['鸡'/130, l='MpServer', x=191.13, y=68.00, z=229.46], EntityChicken['鸡'/131, l='MpServer', x=201.16, y=70.00, z=231.73], EntityItem['item.item.egg'/132, l='MpServer', x=198.95, y=72.00, z=227.52], EntityItem['item.item.egg'/133, l='MpServer', x=204.79, y=72.00, z=227.51], EntityItem['item.item.egg'/134, l='MpServer', x=200.37, y=70.00, z=232.06], EntityChicken['鸡'/136, l='MpServer', x=200.01, y=67.00, z=269.50], EntityChicken['鸡'/137, l='MpServer', x=213.13, y=71.00, z=264.50], EntityCreeper['爬行者'/1545, l='MpServer', x=244.50, y=33.00, z=284.50], EntityChicken['鸡'/138, l='MpServer', x=194.48, y=69.00, z=257.90], EntitySquid['鱿鱼'/1291, l='MpServer', x=229.43, y=59.29, z=328.31], EntitySheep['羊'/141, l='MpServer', x=200.65, y=67.00, z=276.20], EntitySkeleton['骷髅'/525, l='MpServer', x=229.70, y=70.00, z=221.70], EntityBat['蝙蝠'/1942, l='MpServer', x=233.25, y=26.10, z=312.25], EntityChicken['鸡'/152, l='MpServer', x=212.32, y=59.00, z=197.89], EntityChicken['鸡'/156, l='MpServer', x=219.14, y=72.00, z=227.28], EntityChicken['鸡'/157, l='MpServer', x=218.86, y=72.00, z=232.20], EntityChicken['鸡'/158, l='MpServer', x=210.09, y=72.00, z=232.10], EntityItem['item.item.egg'/159, l='MpServer', x=219.11, y=72.00, z=226.80], EntitySkeleton['骷髅'/2207, l='MpServer', x=239.50, y=33.00, z=318.50], EntityChicken['鸡'/161, l='MpServer', x=211.10, y=71.00, z=248.71], EntityChicken['鸡'/162, l='MpServer', x=219.43, y=72.00, z=242.23], EntityChicken['鸡'/164, l='MpServer', x=217.45, y=78.00, z=258.34], EntitySheep['羊'/165, l='MpServer', x=209.52, y=69.00, z=260.70], EntityPig['猪'/167, l='MpServer', x=237.27, y=87.00, z=255.54], EntityChicken['鸡'/168, l='MpServer', x=230.61, y=89.00, z=264.21], EntityItem['item.item.egg'/169, l='MpServer', x=223.27, y=87.00, z=265.19], EntitySheep['羊'/170, l='MpServer', x=231.94, y=89.00, z=261.80], EntitySheep['羊'/179, l='MpServer', x=234.48, y=88.00, z=268.23], EntityChicken['鸡'/180, l='MpServer', x=253.11, y=88.00, z=265.52], EntityItem['item.item.egg'/181, l='MpServer', x=229.08, y=88.00, z=267.92], EntityPig['猪'/196, l='MpServer', x=246.47, y=79.00, z=252.05], EntityPig['猪'/197, l='MpServer', x=254.74, y=89.00, z=260.54], EntitySkeleton['骷髅'/198, l='MpServer', x=241.57, y=87.00, z=268.16], EntityItem['item.item.egg'/2252, l='MpServer', x=219.59, y=72.00, z=243.09], EntitySkeleton['骷髅'/206, l='MpServer', x=253.61, y=61.00, z=279.12], EntityChicken['鸡'/207, l='MpServer', x=255.88, y=90.00, z=280.83], EntityCreeper['爬行者'/2134, l='MpServer', x=238.04, y=55.00, z=344.16], EntityCreeper['爬行者'/2135, l='MpServer', x=236.85, y=55.00, z=341.53], EntityCreeper['爬行者'/2136, l='MpServer', x=238.30, y=55.00, z=345.59], EntityChicken['鸡'/100, l='MpServer', x=187.93, y=68.00, z=212.19], EntityChicken['鸡'/105, l='MpServer', x=188.94, y=68.00, z=236.53], EntityItem['item.item.egg'/106, l='MpServer', x=188.10, y=68.00, z=237.16], EntityItem['item.item.egg'/493, l='MpServer', x=193.78, y=68.00, z=257.30], EntityItem['item.item.brain'/112, l='MpServer', x=186.42, y=63.00, z=283.48], EntityItem['item.item.rottenFlesh'/113, l='MpServer', x=185.09, y=63.00, z=283.88], EntityItem['item.item.egg'/1265, l='MpServer', x=211.57, y=71.00, z=248.89], EntityItem['item.item.brain'/114, l='MpServer', x=185.65, y=63.00, z=284.48], EntityChicken['鸡'/120, l='MpServer', x=192.50, y=69.00, z=204.49], EntityChicken['鸡'/121, l='MpServer', x=205.52, y=65.00, z=200.11], EntityChicken['鸡'/122, l='MpServer', x=204.82, y=71.00, z=202.66]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2738)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 7655148224 bytes (7300 MB) / 9009364992 bytes (8592 MB) up to 17179869184 bytes (16384 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx16384m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.3.2702 Optifine OptiFine_1.12.2_HD_U_C9 25 mods loaded, 25 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID              | Version                  | Source                                        | Signature                                |
	|:------ |:--------------- |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft       | 1.12.2                   | minecraft.jar                                 | None                                     |
	| UCHIJA | mcp             | 9.42                     | minecraft.jar                                 | None                                     |
	| UCHIJA | FML             | 8.0.99.99                | forge-1.12.2-14.23.3.2702.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge           | 14.23.3.2702             | forge-1.12.2-14.23.3.2702.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | smoothfontcore  | 1.12.2-1.12              | minecraft.jar                                 | None                                     |
	| UCHIJA | smoothfont      | 1.12.2-1.12-b1           | SmoothFont-1.12.2-1.12-b1.jar                 | None                                     |
	| UCHIJA | baubles         | 1.5.2                    | Baubles-1.12-1.5.2.jar                        | None                                     |
	| UCHIJA | bibliocraft     | 2.4.3                    | BiblioCraft[v2.4.3][MC1.12.0].jar             | None                                     |
	| UCHIJA | biomesoplenty   | 7.0.1.2389               | BiomesOPlenty-1.12.2-7.0.1.2389-universal.jar | None                                     |
	| UCHIJA | guideapi        | 1.12-2.1.5-60            | Guide-API-1.12-2.1.5-60.jar                   | None                                     |
	| UCHIJA | bloodmagic      | 1.12.2-2.2.12-97         | BloodMagic-1.12.2-2.2.12-97.jar               | None                                     |
	| UCHIJA | thaumcraft      | 6.1.BETA15               | Thaumcraft-1.12.2-6.1.BETA15汉化.jar            | None                                     |
	| UCHIJA | botania         | r1.10-354                | Botania r1.10-354.jar                         | None                                     |
	| UCHIJA | codechickenlib  | 3.1.6.339                | CodeChickenLib-1.12.2-3.1.6.339-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | lunatriuscore   | 1.2.0.42                 | LunatriusCore-1.12.2-1.2.0.42-universal.jar   | None                                     |
	| UCHIJA | ingameinfoxml   | 2.8.2.94                 | InGameInfoXML-1.12.2-2.8.2.94-universal.jar   | None                                     |
	| UCHIJA | inventorytweaks | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJA | jei             | 4.9.1.187                | jei_1.12.2-4.9.1.187.jar                      | None                                     |
	| UCHIJA | nei             | 2.4.1                    | NotEnoughItems-1.12.2-2.4.1.233-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | harvestcraft    | 1.12.2u                  | Pam's HarvestCraft 1.12.2u.jar                | None                                     |
	| UCHIJA | soundphysics    | 1.0.4                    | Sound-Physics-1.12.2.jar                      | None                                     |
	| UCHIJA | texfix          | 4.0                      | TexFix+V-1.12-4.0.jar                         | None                                     |
	| UCHIJA | tcinventoryscan | 2.0.10                   | ThaumicInventoryScanning_1.12.2-2.0.10.jar    | None                                     |
	| UCHIJA | thaumicjei      | 1.2.1                    | ThaumicJEI-1.12.2-1.2.4-9.jar                 | None                                     |
	| UCHIJA | twilightforest  | 3.7.424                  | twilightforest-1.12.2-3.7.424-universal.jar   | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
CorePlugin (SmoothFont-1.12.2-1.12-b1.jar)
  bre.smoothfont.asm.Transformer
CoreModLoader (Sound-Physics-1.12.2.jar)
  com.sonicether.soundphysics.CoreModInjector
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 390.77' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	Launched Version: 1.12.2
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 390.77, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge,LiteLoader'
	Type: Client (map_client.txt)
	Resource Packs: Minecraft-Mod-Language-Modpack.zip
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_C9
	Render Distance Chunks: 64
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 4.6.0 NVIDIA 390.77
	OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
```

**Comment by mingl0280** [comment] 2018-05-26 08:03
Update: This crash can be caused by any operation that has a particle effect. Even using other tools.
Please fix this.

**Comment by Sumguy62** [comment] 2018-05-26 12:34
Please learn to read other bug reports.

**Comment by yunruiwatts** [comment] 2018-05-26 15:39
Duplicate of #858

**Closed as completed** 2018-06-04 10:26 UTC
Labels: bug, duplicate, done
