### ISSUE TITLE
Rotating Hungry Chest with a wrench destroys its contents.

### ISSUE THREAD

**Issue by AnrDaemon** [Azanor/thaumcraft-beta#537] opened 2018-04-27 09:45 UTC
I've found one of my chests facing undesirable and attempted to rotate it with a BC wrench. (Ok, it was EnderIO Yeta Wrench, but still…)
Well, that worked. Kind of. The chest is now facing the right way, but its contents is entirely cleared.

Reproducible with any given BC-compatible wrench.
EnderIO Yeta Wrench
Applied Energistics Nether/Certus Quartz Wrench
Thermal Expansion Crescent Hammer
Forestry Wrench

**Comment by LightniX** [comment] 2018-04-27 11:46
Because this issue is with an other mod i don't think it will be fixed. And i think the Hungry Chest is an entity. If I am right its understandable why it doesn' works.

-LightniX

**Comment by AnrDaemon** [comment] 2018-04-27 11:53
Whatever you think, my task is to report the issue. How would it be resolved, is up to the Azanor, but it MUST be resolved.

P.S.
No need to run around replying to every issue. Especially if one reply has been given already.
If you want notifications of updates - hit "Subscribe".
And duplicating your name in every post makes no sense either. It is already added to your every post by the system.

**Comment by Azanor** [comment] 2018-05-02 15:56
*shrug* not really my problem. I'll take a look if there is something in my control to improve that behaviour, but it is defintely not a bug.

**Comment by Azanor** [comment] 2018-05-04 07:35
*Sigh* fine

I took another look and the odd thing is that this only seems to happen with the hungry chest - all my other blocks rotate fine. The only difference is that the hungry chest is basically a copy of the vanilla chest which should make it LESS likely to behave this way, but apparently that is not the case. I will fiddle some more.

**Comment by HenryLoenwind** [comment] 2018-05-04 07:38
Probably half the required code is in `Block` behind ´block===CHEST´ checks again. Took me ages to find all pieced for slabs...

**Comment by Azanor** [comment] 2018-05-04 07:44
Basically yes. Its is the shouldRefresh method in TileEntity. I override it for my own TE's, but since I just use the vanilla chest TE for the hungry chest it uses the vanilla version which was causing the TE's to get wiped when the blockstate changed.

**Closed** 2018-05-04 12:13 UTC
Labels: bug, solved
