### ISSUE TITLE
[B20] Thaumatorium non-functional

### ISSUE THREAD

**Issue by katzenpapst** [Azanor/thaumcraft-beta#1243] opened 2018-08-05 13:47 UTC
I can no longer use the Thaumatorium since B20. I can put in the ingredient, it then shows the possible products, but I cannot actually select them. It plays the sound effect if I click them, but that doesn't actually do anything.

**Comment by wamc2017** [comment] 2018-08-05 13:48
Maybe a dupe of #1239

Are you playing on a server?

**Comment by katzenpapst** [comment] 2018-08-05 14:04
Yes, I am.

**Closed** 2018-08-08 07:53 UTC
Labels: bug, done, duplicate

**Comment by BlockheadDev** [comment] 2018-08-12 03:31
@katzenpapst Can you please port Amun-Ra (The galacticraft addon) to 1.11.2? It would really mean a lot!

**Comment by katzenpapst** [comment] 2018-08-12 13:46
This is off topic here. 

And, meh. Last time I tried it, I was frustrated AF. I have been considering trying to redo it for the current version, but now, there's again an ever newer one....

That mod is open source, though. You are free to try to do it yourself.
