### ISSUE TITLE
Game crashes while trying to use Focal Manipulator?

### ISSUE THREAD

**Issue by LokiWiz** [Azanor/thaumcraft-beta#251] opened 2018-02-09 22:29 UTC
When trying to move the medium glyph over the box, the game crashes. This has happened every time, at the exact same time.

**Comment by PyroManiac999** [comment] 2018-02-09 23:33
duplicate of #237 I guess

**Comment by Cenotaffio** [comment] 2018-02-10 08:11
this was already reported in other 2 posts

**Comment by darklex55** [comment] 2018-02-10 18:32
No, this is not like the other posts. I'm trying to make the first focus the Thaumonomicon instructs you to, but every time I try to place the second modifier the game crashes. I tried both adding the "fire" after the "Touch" and the other way around but nothing works.
[crash-2018-02-10_20.29.39-client.txt](https://github.com/Azanor/thaumcraft-beta/files/1713671/crash-2018-02-10_20.29.39-client.txt)

**Comment by Goof245** [comment] 2018-02-11 01:22
Read the stacktrace dude, this is the same crash. Basically the code that tries to check for gem connectivity is broken right now.

**Closed** 2018-02-14 06:55 UTC
Labels: bug, done, duplicate
