### ISSUE TITLE
[BETA 17] Flux Condenser Ticking Block Entity Crash

### ISSUE THREAD

**Issue by Cknfrydsteak** [Azanor/thaumcraft-beta#1173] opened 2018-07-19 23:56 UTC
It seems likely there are problems with the flux condenser.  Setup was a valved pipe from an alembic (empty) to a flux condenser with a single lattice above and an essentia jar immediately below.  The condenser was still processing flux during the time of the crash.  Crash was induced by unloading and reloading the dimension (via entering and leaving) with the player.  Interestingly, the dimension was reloaded twice without issue prior to this, and the condenser only crashes any clients which load the affected chunk instead of the whole server.

I can't be sure this is truly a problem with Thaumcraft given that this happened in a modpack with several other mods loaded, but the crash report seems to indicate so.

Crash report:  https://paste.dimdev.org/oqamivafal.mccrash

Update:  Removing the condenser with MCEdit resolved the client crashing.

**Comment by wamc2017** [comment] 2018-07-20 00:03
Dupe of #1095

**Closed** 2018-07-20 07:29 UTC
Labels: bug, done, duplicate
