### ISSUE TITLE
Banner and essentia vials are causing java-error

### ISSUE THREAD

**Issue by Ineffizienz** [Azanor/thaumcraft-beta#1337] opened 2018-08-20 19:28 UTC
Hi there,

I'm hosting a little server for some folks and I'm using thaumcraft 6 in the version beta 22. Also the server is running on Forge 14.23.4.2756. If I'm trying to put some of the essentia on a banner to be able to get the icon, e.g. for bestia the minecraft-server itself is throwing some error. Also the icon does not appear on the banner. My java-skills are very little so I'm apologizing if this error is not related to this issue.

` Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.item.EnumDyeColor.func_193350_e()I
at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_151]
at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_151]
at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NoSuchMethodError: net.minecraft.item.EnumDyeColor.func_193350_e()I
at thaumcraft.common.tiles.misc.TileBanner.getColor(TileBanner.java:73) ~[TileBanner.class:?]
at thaumcraft.common.blocks.basic.BlockBannerTC.func_180639_a(BlockBannerTC.java:104) ~[BlockBannerTC.class:?]
at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:449) ~[or.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) ~[pa.class:?]
at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_151]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_151]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]`

Greeting
Ineffizienz

**Comment by F9Alejandro** [comment] 2018-08-20 21:36
It has to do with no method found for item and banner dye color (or at least what is trying to be passed to them)

**Comment by CubedBits** [comment] 2018-08-20 22:37
I can confirm that this also occurs with forge version 14.23.4.2705, but it only happens on dedicated servers. Not single player or open to LAN.

Looking into the class `net.minecraft.item.EnumDyeColor` i see that it has two methods annotated as `@SideOnly(Side.CLIENT)` Those being: `getDyeColorName()` and `getColorValue()` 

I don't imagine they would be included in the server since they are marked as client only, so perhaps the banner is trying to use them but can't find them. Thus a NoSuchMethodError would be thrown?

The Minecraft method names are obfuscated in the log so I can't really confirm my idea.

**Comment by F9Alejandro** [comment] 2018-08-20 22:55
Forge has a file the denotes the different functions and what they do. There is also a map file that provides what the functions do and remaps them for easy use (actual names not just func_xxxx)

**Closed** 2018-08-24 09:06 UTC
Labels: bug, done
